### DISCUSSION TITLE
Unclear error and recovery on active environment post blueprint update

### DISCUSSION THREAD

**Discussion by 1800joe** [noop-inc/documentation#154] [Bugs]
v0.10.3

- Error occurred after saving blueprint.yaml. See below 
- Toggling env switch produces same error.
- Triggering build through superficial change (whitespace) partially resolved. launch services stalled see below
- Launch services eventually fails
- Hard reset Workshop and changing the blueprint before restart led to a resolution.

Eventually got it working, but something interesting is going on.

Take this blueprint:

```yaml
name: Next Site
components:
  - name: NextSite
    type: service
    image: node:20-alpine
    port: 3000
    build:
      # 👇 intentional/selective ordering of 'copy' and 'run' steps
      # will make it possible to take advantage of cached build
      # layers in Noop Workshop (TLDR - speedier subsequent builds!)
      steps:
        # first copy over dependency files and install...
        - copy: [package.json, yarn.lock]
        - run: yarn install --immutable
        # ...then copy over project files before generating build assets
        - copy: [next.config.mjs, tsconfig.json]
        - copy: public/
        - copy: src/
        - run: yarn build
    runtime:
      command: yarn start

  # - name: NextStatic
  #   type: static
  #   image: node:20-alpine
  #   build:
  #     steps:
  #       - copy: [package.json, yarn.lock]
  #       - run: yarn install --immutable
  #       - copy: [next.config.mjs, tsconfig.json]
  #       - copy: public/
  #       - copy: src/
  #       - run: yarn build
  #       - directory: build/
routes:
  - target:
      component: NextSite
```

If I uncomment the static, I get the ambiguous errors. Otherwise it works. Also worth noting that that state appears unrecoverable without a reset + "fixing" of blueprint.

![Screenshot 2024-04-26 at 1 16 45 PM](https://github.com/noop-inc/documentation/assets/3111670/b97106a0-a1aa-45ed-9cbd-ce65cc1f60ac)

![Screenshot 2024-04-26 at 1 22 42 PM](https://github.com/noop-inc/documentation/assets/3111670/44316c83-279d-4620-8354-413bca43305e)

![Screenshot 2024-04-26 at 2 16 33 PM](https://github.com/noop-inc/documentation/assets/3111670/0af9ceb7-4dbb-4cbc-b67b-ac9a2163ee7e)
