### DISCUSSION TITLE
Specifics of multi-stage builds in app.yml

### DISCUSSION THREAD

**Discussion by nprimmer** [noop-inc/documentation#43] [Questions] [answered]
When performing a multi-stage build within app.yml, the ordering of steps and association with a stage is unclear, at least based on the current documentation:
https://docs.noop.dev/en/articles/7905578-application-manifest-app-yml

- When performing multi-stage builds, is the published container the image in the final stage in the build, or is it the "main" image?
- How can I designate which "stage" a directive takes place in?

The dockerfile equivalent of what I'm trying to do is:
FROM golang:1.21 AS builder
WORKDIR /build
COPY backend/* /build/
RUN go build -o backend ./...

FROM alpine:latest
COPY --from=builder /build/backend /app/
EXPOSE 8080
CMD ["/app/backend"]

**Comment by 1800joe** [comment]
Currently we only support a single base image. The published container is the image in the final step of the build process.

EXPOSE maps to `port` in the service runtime config and CMD to `command` also in the service runtime config.

**Comment by 1800joe** [comment, marked as answer]
I spoke too soon. We do support multi-stage builds. See the following example:

The copy step referencing `main` refers to the original build image.

``` 
 - name: WebsiteStatic
    type: service
    image: node:18-alpine
    root: website-static/
    build:
      steps:
        - directory: /website-static
        - copy: package*.json
          destination: ./
        - run: npm ci
        - copy: index.html
        - copy: vite.config.js
        - copy: public/
        - copy: src/
        - run: npm run build
        - image: nginx:1-alpine
          stage: nginx
        - copy: website-static/dist
          destination: /usr/share/nginx/html/
          from: main
        - copy: nginx.conf
          destination: /etc/nginx
    runtime:
      command: 'nginx -g "daemon off;"'
      variables:
        NGINX_ENTRYPOINT_QUIET_LOGS: '1'

```
