### DISCUSSION TITLE
Deployment fails with YamlParseError

### DISCUSSION THREAD

**Discussion by nathanielks** [noop-inc/documentation#87] [Bugs] [answered]
## Description

After toggling an environment's activation switch, I got an error:

```
POST /local/orgs/cd21f592e1/apps/4/envs/1/deploys
statusCode: 500
code: YamlParseError
message: |
  Implicit keys need to be on a single line at line 10, column 1:

        required: true
  <<<<<<< HEAD
  ^
cause:
  statusCode: 500
  code: YAMLParseErrorWrap
  message: |
    Implicit keys need to be on a single line at line 10, column 1:

          required: true
    <<<<<<< HEAD
    ^
```
![Screenshot 2024-01-23 at 11 32 34 AM](https://github.com/noop-inc/documentation/assets/314009/6b3220d1-e063-44a6-a9f4-04b538600fb3)

## Files

`.noop/app.yml`:
```yaml
---
components:
  - name: WordPress
    type: service
    image: wordpress:6.4.1-php8.2-apache
    port: 80
    build: &buildwp
      steps:
        - directory: /usr/src/wordpress
        - run: find /etc/apache2 -name '*.conf' -type f -exec sed -ri -e "s!/var/www/html!/usr/src/wordpress/web!g" -e "s!Directory /var/www/!Directory /usr/src/wordpress/web!g" '{}' +
        - copy: bin/
        - run: sh bin/install-composer.sh
        - run: sh bin/install-wpcli.sh
        - run: apt update && apt install -y jq
        - copy: wp-cli.yml
        - copy: composer.json
        - copy: composer.lock
        - run: composer install
        - copy: config/
        - copy: web/
    runtime: &runtimewp
      resources:
        - MySQLDatabase
        - S3Bucket
      variables:
        STACK_ID:
          $stack: id
        APP_NAME:
          $app: name
        WP_ENV:
          $env:
            if:
              - var: production
              - production
              - development
        AWS_REGION:
          $env: region
        DB_HOST:
          $resources: MySQLDatabase.host
        DB_NAME:
          $resources: MySQLDatabase.database
        DB_USER:
          $resources: MySQLDatabase.username
        DB_PASSWORD:
          $resources: MySQLDatabase.password
        S3_UPLOADS_BUCKET:
          $resources: S3Bucket.bucket
        S3_UPLOADS_ENDPOINT:
          $resources: S3Bucket.endpoint
        S3_UPLOADS_REGION:
          $env: region
  - name: WordPressCron
    type: task
    image: curlimages/curl:latest
    cron: '* * * * *'
    runtime:
      command: curl --fail-with-body http://localstack/wp/wp-cron.php
  - name: SaltGenerator
    type: task
    image: stedolan/jq:latest
    build:
      steps:
        - copy: bin/salts.sh 
          destination: /tmp/salts.sh
    runtime:
      entrypoint: ''
      command: sh /tmp/salts.sh
  - name: WordPressInstaller
    type: task
    image: wordpress:6.4.1-php8.2-apache
    build: *buildwp
    runtime: 
      <<: *runtimewp
      command: sh -c bin/install-wordpress.sh
      entrypoint: ''

routes:
  - target:
      component: WordPress

resources:
  - name: MySQLDatabase
    type: mysql
  - name: S3Bucket
    type: s3
```

The repository (this is a different repo from https://github.com/orgs/noop-inc/discussions/85): 
[wordpress.zip](https://github.com/noop-inc/documentation/files/14027516/wordpress.zip)
