### DISCUSSION TITLE
Database resource names are being passed through without alteration in Noop Cloud

### DISCUSSION THREAD

**Discussion by nprimmer** [noop-inc/documentation#99] [Bugs]
Discovered while troubleshooting an issue that the resource name for a database resource is being passed directly through as the resource name to the RDS instance being created for it:
```
code: AmazonError
message: backend systems error
cause:
  code: InvalidParameterValueWrap
  message: DatabaseName Database cannot be used.  It is a reserved word for this engine
context:
  service: rds
  action: createDBCluster
```
