### ISSUE TITLE
Local Proxy Endpoint fails to create

### ISSUE THREAD

**Issue by 1800joe** [noop-inc/documentation#58]
It looks like the validation fails when the hostname contains a port.

this could be a useful way to run a process outside the context of Noop

**Comment by 1800joe** [comment]
```yaml
code: ValidationError
message: Payload failed to validate
context:
  payload:
    endpointId: /local/endpoints/5
    routes:
      - name: d
        target:
          proxyHost: localhost:4321
          proxySecure: true
        pattern: /docs/**
      - name: Project Route
        target:
          projects:
            - /local/projects/5
  errors:
    - instancePath: /routes/0/target
      schemaPath: '#/properties/routes/items/properties/target/oneOf/0/required'
      keyword: required
      params:
        missingProperty: projects
      message: must have required property 'projects'
    - instancePath: /routes/0/target/proxyHost
      schemaPath: '#/properties/routes/items/properties/target/oneOf/0/properties/proxyHost/false
        schema'
      keyword: false schema
      params: {}
      message: boolean schema is false
    - instancePath: /routes/0/target/proxySecure
      schemaPath: '#/properties/routes/items/properties/target/oneOf/0/properties/proxySecure/false
        schema'
      keyword: false schema
      params: {}
      message: boolean schema is false
    - instancePath: /routes/0/target/proxyHost
      schemaPath: '#/properties/routes/items/properties/target/oneOf/1/properties/proxyHost/format'
      keyword: format
      params:
        format: hostname
      message: must match format "hostname"
    - instancePath: /routes/0/target
      schemaPath: '#/properties/routes/items/properties/target/oneOf/2/required'
      keyword: required
      params:
        missingProperty: redirectUrl
      message: must have required property 'redirectUrl'
    - instancePath: /routes/0/target/proxyHost
      schemaPath: '#/properties/routes/items/properties/target/oneOf/2/properties/proxyHost/false
        schema'
      keyword: false schema
      params: {}
      message: boolean schema is false
    - instancePath: /routes/0/target/proxySecure
      schemaPath: '#/properties/routes/items/properties/target/oneOf/2/properties/proxySecure/false
        schema'
      keyword: false schema
      params: {}
      message: boolean schema is false
    - instancePath: /routes/0/target
      schemaPath: '#/properties/routes/items/properties/target/oneOf/3/required'
      keyword: required
      params:
        missingProperty: statusCode
      message: must have required property 'statusCode'
    - instancePath: /routes/0/target/proxyHost
      schemaPath: '#/properties/routes/items/properties/target/oneOf/3/properties/proxyHost/false
        schema'
      keyword: false schema
      params: {}
      message: boolean schema is false
    - instancePath: /routes/0/target/proxySecure
      schemaPath: '#/properties/routes/items/properties/target/oneOf/3/properties/proxySecure/false
        schema'
      keyword: false schema
      params: {}
      message: boolean schema is false
    - instancePath: /routes/0/target
      schemaPath: '#/properties/routes/items/properties/target/oneOf/4/required'
      keyword: required
      params:
        missingProperty: blackhole
      message: must have required property 'blackhole'
    - instancePath: /routes/0/target/proxyHost
      schemaPath: '#/properties/routes/items/properties/target/oneOf/4/properties/proxyHost/false
        schema'
      keyword: false schema
      params: {}
      message: boolean schema is false
    - instancePath: /routes/0/target/proxySecure
      schemaPath: '#/properties/routes/items/properties/target/oneOf/4/properties/proxySecure/false
        schema'
      keyword: false schema
      params: {}
      message: boolean schema is false
    - instancePath: /routes/0/target
      schemaPath: '#/properties/routes/items/properties/target/oneOf'
      keyword: oneOf
      params:
        passingSchemas: null
      message: must match exactly one schema in oneOf
```
